# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0002_auto_20190417_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artistName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
