# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 10:29
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0006_auto_20190418_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_track',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='songs/'),
        ),
    ]
