# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0008_auto_20190421_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
